### ISSUE TITLE
readme.mdの通りに設定したが動かない

### ISSUE THREAD

**Issue by orarange** [free-RT/gom-bot#8]
```
Traceback (most recent call last):
  File "/workspaces/gom-bot/main.py", line 11, in <module>
    bot.run(token=os.environ["TOKEN"])
  File "/home/codespace/.local/share/virtualenvs/gom-bot-axrAplyU/lib/python3.10/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/codespace/.local/share/virtualenvs/gom-bot-axrAplyU/lib/python3.10/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/codespace/.local/share/virtualenvs/gom-bot-axrAplyU/lib/python3.10/site-packages/discord/client.py", line 663, in start
    raise TypeError("unexpected keyword argument(s) %s" % list(kwargs.keys()))
TypeError: unexpected keyword argument(s) ['token']
```
@ysmreg

**Comment by yaakiyu** [comment]
直した。

**Comment by minato37103710** [comment]
thx
